version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/selenium-test # directory where steps will run

    docker: # run the steps with Docker

    - image: circleci/android:api-26-alpha # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

    - checkout # check out source code to working directory

    - run:
        name: Install android sdk
        command: |
          sudo apt-get install software-properties-common -y

          sudo apt-get update -y

          wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz

          tar -xvf android-sdk_r24.2-linux.tgz
          cd android-sdk-linux/tools

          ./android update sdk yes | sudo sdkmanager --licenses

          vi ~/.zshrc << EOT

          export PATH=${PATH}:$HOME/sdk/android-sdk-linux/platform-tools:$HOME/sdk/android-sdk-linux/tools:$HOME/sdk/android-sdk-linux/build-tools/22.0.1/

          EOT

          yes | sdkmanager --licenses

    - run:
        name: Search maven package
        command: apt-cache search maven

    - run:
        name: Install maven
        command: sudo apt-get install maven

    - run:
        name: Veryfication maven
        command: mvn -version

    - run:
        name: Install bundle
        command: gem install bundle

    - restore_cache:
        key: gems-{{ checksum "Gemfile.lock" }}

    - run:
        name: Install and update danger
        command: |
          bundle update danger
          bundle install --path vendor/bundle

    - save_cache:
        paths:
        - vendor/bundle
        key: gems-{{ checksum "Gemfile.lock" }}

    - run:
        name: Check
        command: mvn validate

    - run:
        name: Run danger
        command: bundle exec danger