version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/selenium-test/src/java # directory where steps will run

    docker: # run the steps with Docker

    - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

    - checkout # check out source code to working directory

    - run:
        name: Install gem
        #        command:  |
        #          mkdir /tmp/ruby && cd /tmp/ruby
        #          wget http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p327.tar.gz
        #          tar xfvz ruby-1.9.3-p327.tar.gz
        #          cd ruby-1.9.3-p327
        #          ./configure
        #          make
        #          sudo make install
        command:  |
          rm -rf /usr/local/lib/ruby/site_ruby/
          brew uninstall ruby
          gem install psych
          brew install ruby

    - run:
        name: Install bundle
        command: gem install bundle

    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        key: selenium-test-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: selenium-test-{{ checksum "pom.xml" }}

    - run:
        name: Check
        command: mvn validate

    - run:
        name: Run danger
        command: bundle exec danger