version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/selenium-test/src/java # directory where steps will run

    docker: # run the steps with Docker

    - image: circleci/ruby:2.3-node-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

    - checkout # check out source code to working directory

    - run:
        name: Search maven package
        command: apt-cache search maven

    - run:
        name: Install maven
        command: sudo apt-get install maven

    - run:
        name: Veryfication maven
        command: mvn -version

    - run:
        name: Install bundle
        command: gem install bundle

    - run: bundle install --path vendor/bundle
      - save_cache:
          paths:
          - vendor/bundle
          key: gems-{{ checksum "Gemfile.lock" }}

    - run:
        name: Check
        command: mvn validate

    - run:
        name: Run danger
        command: bundle exec danger